### ISSUE TITLE
Buffering a large FeatureCollection of points only includes some of the points?

### ISSUE THREAD

**Issue by veltman** [Turfjs/turf-buffer#12]
I tried using turf-buffer to get a buffer around a FeatureCollection of about 1800 points:

![screen shot 2015-02-10 at 11 20 15 am](https://cloud.githubusercontent.com/assets/2120446/6131272/b98ce7b8-b118-11e4-9254-f37be7c8de52.png)

```js
var buffered = turf.buffer(
    points,
    0.25,
    "miles"
  );
```

The buffer result only seems to have incorporated a fraction of the points.

![screen shot 2015-02-10 at 11 20 30 am](https://cloud.githubusercontent.com/assets/2120446/6131273/b98df018-b118-11e4-9b3f-c58606b976de.png)

If I manually buffer EACH point feature individually, and then merge all the resulting polygons, it does incorporate them all:

```js
var individuallyBuffered = turf.merge({
  "type": "FeatureCollection",
  "features": points.features.map(function(feature){
    return turf.buffer(feature,0.25,"miles").features[0];
  })
});
```

Pink is the results from one-by-one buffering and green is the result from buffering the whole collection:

![screen shot 2015-02-10 at 11 32 42 am](https://cloud.githubusercontent.com/assets/2120446/6131271/b98a5b74-b118-11e4-8153-17ff04d6712f.png)

Something I'm missing about how this is supposed to work?

This is the original GeoJSON of points:

https://gist.github.com/veltman/35209c89318be09dee33

**Comment by morganherlocker** [comment]
Thanks for reporting, and the clear writeup. This appears to be a bug. I will take a look and update here w/ more info.

**Comment by seadour** [comment]
I am having a similar issue. See jsfiddle here: https://jsfiddle.net/fq28yddb/2/

It appears that the buffers are missing where they would overlap with other buffers that were drawn first.

**Comment by morganherlocker** [comment]
@veltman looks like jsts was randomly dropping points. I have a branch that works around this. Here is your point dataset running on the new branch:

![](https://dl.dropbox.com/s/7koojjcxsk0pvon/Screenshot%202015-03-17%2014.49.04.png?dl=0)

The new behavior is to output a featurecollection of unmerged polygons. To get a unioned buffer, you would send a MultiPoint instead.

[PR](https://github.com/Turfjs/turf-buffer/pull/19)

**Comment by morganherlocker** [comment]
fixed https://github.com/Turfjs/turf-buffer/commit/7baff7fac5ec5ae47ad24510f042c6784237cf04
