### ISSUE TITLE
Unknown GeoJSON type: undefined

### ISSUE THREAD

**Issue by sheon** [Turfjs/turf-buffer#26]
I am trying to check features drawn using OL 3 for intersections. Features are all lineStrings. 
I use the following code where i get the Unknown GeoJSON type error:

lineStringdraw.on('drawend', function(e2) {
    var featureEnd = e2.feature;
    checkIntersection(featureEnd);
});

function checkIntersection(currentFeature){
	var features = vectorLayer.getSource().getFeatures();
	var geoJSON = new ol.format.GeoJSON();
       geoJSON = geoJSON.writeFeature(currentFeature);
	for (i=0; (features.length)>i;i++){
			var feature = features[i];
		       geoJSON_i = geoJSON.writeFeature(feature);
			var intersectionStatus = turf.intersect(geoJSON,geoJSON_i);
			$('#infoList').append(intersectionStatus);	
	}		
}

here is piece of the OL3 GeoJSON:
     {"type":"Feature","geometry":{"type":"LineString","coordinates":[[-8236104.129670544,4977029.890789877],[-8236634.411554272,4974407.145256842]]},"properties":null}

comparing to the turf standard, they pretty much look the same except the turf uses single quotations instead. Shouldn't they be compatible as long as both follow the same standard as GeoJSON? Or am I missing something here?

**Comment by tmcw** [comment]
```js
{"type":"Feature","geometry":{"type":"LineString","coordinates":[[-8236104.129670544,4977029.890789877],[-8236634.411554272,4974407.145256842]]},"properties":null}
```

This is invalid GeoJSON - properties cannot be `null` - properties must be an object. Please reopen if this issue persists after fixing that error.

**Comment by BrodaNoel** [comment]
I'm getting the same "Unknown GeoJSON type" issue.
This is the shape that I am using:

```JSON
{
  "geometry": {
    "coordinates": [ 46.45790205489638, 6.846404385911114 ],
    "type": "Point"
  },
  "properties": {
    "id": "00cf8729-8a29-4239-90ca-5ebc0ab25ea4"
  },
  "type": "Feature"
}
```

Am I doing something wrong?

**Comment by dasheck0** [comment]
Not sure if this is still relevant. I ran into the same issue. The function I was using (`clusterDbscan`) expected a FeatureCollection and not a feature. So I created one and it worked (see code below)

```
const { point, featureCollection } = require('@turf/turf');

const feature = point([0,0], { name: 'origin'});
const collection = featureCollection([point]);

// const clustered = clustersDbscan(feature, 5);  --> does not work
// const clustered = clustersDbscan(collection, 5); --> works
```
